<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>ANI animated cursor file format optimizer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Optimizer.Ani.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Hawkynt.FileFormats.Images\Hawkynt.FileFormats.Images.csproj" />
    <ProjectReference Include="..\..\FileFormat.Core\FileFormat.Core.csproj" />
    <ProjectReference Include="../../Crush.Core/Crush.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>
</Project>
