using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using FileFormat.Core;

namespace Hawkynt.FileFormats.Images.Tests;

/// <summary>
/// Holds image readers to files made outside this repository.
/// </summary>
/// <remarks>
/// <c>WriterOracleTests</c> asks an external reader what it makes of bytes written here. This is the
/// inverse check: <c>build-reader-oracle-corpus.sh</c> asks an external writer to make the encoded
/// file, asks an external decoder what picture those exact bytes mean, and records both. The test
/// then requires this package's reader to reconstruct the same pixels, within the tolerance recorded
/// for deliberately lossy formats.
/// <para/>
/// The generated corpus stays outside version control. Set <c>READER_ORACLE_CORPUS</c> to its root
/// when running this explicit conformance test.
/// </remarks>
[TestFixture]
[Category("Conformance")]
public sealed class ReaderOracleCorpusTests {

  private const string _CORPUS_VARIABLE = "READER_ORACLE_CORPUS";
  private const string _MANIFEST = "manifest.tsv";

  [Test]
  [Explicit("Consumes a corpus generated by Tools/parity/build-reader-oracle-corpus.sh.")]
  public void ReaderOracleCorpus_ExternalWriterBytesDecodeLikeExternalReference() {
    var root = Environment.GetEnvironmentVariable(_CORPUS_VARIABLE);
    if (string.IsNullOrWhiteSpace(root))
      Assert.Inconclusive($"Set {_CORPUS_VARIABLE} to a corpus generated by Tools/parity/build-reader-oracle-corpus.sh.");

    var manifest = Path.Combine(root!, _MANIFEST);
    Assert.That(File.Exists(manifest), Is.True, $"Reader-oracle manifest does not exist: {manifest}");

    var png = FormatRegistry.GetEntry(ImageFormat.Png);
    Assert.That(png, Is.Not.Null, "PNG must be available to read the external reference images.");

    var failures = new List<string>();
    var cases = 0;

    foreach (var line in File.ReadLines(manifest)) {
      if (string.IsNullOrWhiteSpace(line) || line.StartsWith('#'))
        continue;

      ++cases;
      var fields = line.Split('\t');
      if (fields.Length != 6) {
        failures.Add($"manifest line {cases}: expected 6 tab-separated fields, got {fields.Length}");
        continue;
      }

      var producerText = fields[0];
      var decoderText = fields[1];
      var formatText = fields[2];
      var encodedPath = Path.GetFullPath(Path.Combine(root, fields[3]));
      var referencePath = Path.GetFullPath(Path.Combine(root, fields[4]));

      if (!Enum.TryParse<ConformanceOracle>(producerText, ignoreCase: false, out var producer)
          || producer == ConformanceOracle.None) {
        failures.Add($"{formatText}: unknown external writer '{producerText}'");
        continue;
      }

      if (!Enum.TryParse<ConformanceOracle>(decoderText, ignoreCase: false, out var decoder)
          || decoder == ConformanceOracle.None) {
        failures.Add($"{formatText}: unknown external decoder '{decoderText}'");
        continue;
      }

      if (!Enum.TryParse<ImageFormat>(formatText, ignoreCase: false, out var format)
          || format == ImageFormat.Unknown) {
        failures.Add($"{formatText}: not a registered ImageFormat name");
        continue;
      }

      if (!int.TryParse(fields[5], NumberStyles.None, CultureInfo.InvariantCulture, out var tolerance)
          || tolerance is < 0 or > byte.MaxValue) {
        failures.Add($"{formatText}: invalid per-channel tolerance '{fields[5]}'");
        continue;
      }

      if (!File.Exists(encodedPath)) {
        failures.Add($"{formatText}: encoded file is missing: {encodedPath}");
        continue;
      }

      if (!File.Exists(referencePath)) {
        failures.Add($"{formatText}: reference image is missing: {referencePath}");
        continue;
      }

      var entry = FormatRegistry.GetEntry(format);
      if (entry == null) {
        failures.Add($"{formatText}: registry entry is missing");
        continue;
      }

      RawImage? actual;
      RawImage? reference;
      try {
        actual = entry.LoadRawImageOrThrow?.Invoke(new FileInfo(encodedPath));
      } catch (Exception exception) {
        failures.Add($"{formatText}: our reader threw on {producer.DisplayName()} output: {exception.Message}");
        continue;
      }

      try {
        reference = png!.LoadRawImageOrThrow?.Invoke(new FileInfo(referencePath));
      } catch (Exception exception) {
        failures.Add($"{formatText}: could not read the {decoder.DisplayName()} reference PNG: {exception.Message}");
        continue;
      }

      if (actual == null) {
        failures.Add($"{formatText}: our reader returned no picture for {producer.DisplayName()} output");
        continue;
      }

      if (reference == null) {
        failures.Add($"{formatText}: {decoder.DisplayName()} produced no readable reference picture");
        continue;
      }

      var difference = _Compare(actual, reference, tolerance);
      if (difference != null)
        failures.Add($"{formatText}: {producer.DisplayName()} -> our reader disagrees with {decoder.DisplayName()}: {difference}");
    }

    Assert.Multiple(() => {
      Assert.That(cases, Is.GreaterThan(0), "The reader-oracle manifest contains no generated cases.");
      Assert.That(failures, Is.Empty, string.Join(Environment.NewLine, failures));
    });
  }

  private static string? _Compare(RawImage actual, RawImage reference, int tolerance) {
    if (actual.Width != reference.Width || actual.Height != reference.Height)
      return $"geometry {actual.Width}x{actual.Height}, reference {reference.Width}x{reference.Height}";

    RawImage actualBgra;
    RawImage referenceBgra;
    try {
      actualBgra = PixelConverter.Convert(actual, PixelFormat.Bgra32);
      referenceBgra = PixelConverter.Convert(reference, PixelFormat.Bgra32);
    } catch (Exception exception) {
      return "could not normalize both pictures to BGRA32: " + exception.Message;
    }

    if (actualBgra.PixelData.Length != referenceBgra.PixelData.Length)
      return $"normalized byte counts differ ({actualBgra.PixelData.Length} vs {referenceBgra.PixelData.Length})";

    var different = 0;
    var greatestDifference = 0;
    var firstDifferentPixel = -1;

    for (var i = 0; i < actualBgra.PixelData.Length; ++i) {
      var difference = Math.Abs(actualBgra.PixelData[i] - referenceBgra.PixelData[i]);
      if (difference <= tolerance)
        continue;

      ++different;
      greatestDifference = Math.Max(greatestDifference, difference);
      if (firstDifferentPixel < 0)
        firstDifferentPixel = i / 4;
    }

    return different == 0
      ? null
      : $"{different} channel samples differ beyond ±{tolerance}; max difference {greatestDifference}; first pixel {firstDifferentPixel}";
  }
}
