<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Atari 8-bit Graphics 9+ (.gr9p) screens.</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FileFormat.Graphics9Plus.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../FileFormat.Core/FileFormat.Core.csproj" />
    <ProjectReference Include="../../FileFormat.Core.Generators/FileFormat.Core.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
