using System;
using System.Linq;
using FileFormat.Core;
using FileFormat.IffDctv;

namespace FileFormat.IffDctv.Tests;

[TestFixture]
public sealed class IffDctvWriterTests {

  [Test]
  [Category("Unit")]
  public void FromRawImage_Null_ThrowsArgumentNullException() {
    Assert.Throws<ArgumentNullException>(() => IffDctvFile.FromRawImage(null!));
  }

  /// <remarks>
  /// The synchronisation sequence occupies 256 pixels at each end of the top line, so a screen
  /// narrower than 264 pixels cannot carry it. Approximating it would produce a file no DCTV unit
  /// would recognise, which is worse than refusing.
  /// </remarks>
  [Test]
  [Category("Unit")]
  public void FromRawImage_TooNarrow_IsRefusedByName() {
    var ex = Assert.Throws<ArgumentException>(() => IffDctvFile.FromRawImage(_Blank(262, 16)));
    Assert.That(ex!.Message, Does.Contain("264"));
  }

  [Test]
  [Category("Unit")]
  public void FromRawImage_TooWide_IsRefusedByName() {
    var ex = Assert.Throws<ArgumentException>(() => IffDctvFile.FromRawImage(_Blank(2050, 4)));
    Assert.That(ex!.Message, Does.Contain("2048"));
  }

  /// <remarks>One composite sample straddles two pixels, so an odd width strands the last one.</remarks>
  [Test]
  [Category("Unit")]
  public void FromRawImage_OddWidth_IsRefusedByName() {
    var ex = Assert.Throws<ArgumentException>(() => IffDctvFile.FromRawImage(_Blank(321, 16)));
    Assert.That(ex!.Message, Does.Contain("even width"));
  }

  [Test]
  [Category("Unit")]
  public void FromRawImage_TooTall_IsRefusedByName() {
    var ex = Assert.Throws<ArgumentException>(() => IffDctvFile.FromRawImage(_Blank(320, 1025)));
    Assert.That(ex!.Message, Does.Contain("1024"));
  }

  /// <remarks>
  /// The colour map is not a palette in the usual sense: it is the set of analogue levels the Amiga
  /// had to put on its video output for the DCTV box to read the sample nibbles back. Writing any
  /// other sixteen colours would hand the unit a different waveform, so it is copied verbatim from
  /// genuine DCTV files and must stay that way.
  /// </remarks>
  [Test]
  [Category("Unit")]
  public void ColourMap_IsTheOneGenuineFilesCarry() {
    Assert.That(IffDctvCodec.ColourMap, Is.EqualTo(new byte[] {
      0x00, 0x00, 0x00, 0x77, 0x88, 0x66, 0x77, 0x77, 0x88, 0x77, 0x88, 0x88,
      0x88, 0x77, 0x66, 0x88, 0x88, 0x66, 0x88, 0x77, 0x88, 0x88, 0x88, 0x88,
      0x00, 0x00, 0x11, 0x77, 0x88, 0x77, 0x77, 0x77, 0x99, 0x77, 0x88, 0x99,
      0x88, 0x77, 0x77, 0x88, 0x88, 0x77, 0x88, 0x77, 0x99, 0x88, 0x88, 0x99,
    }));
  }

  /// <remarks>
  /// The sequence is generated by a shift register seeded with 125 and fed back through 390. Its
  /// first bits are recorded here because every genuine DCTV file starts with exactly these, and a
  /// re-derived sequence would simply be the wrong one.
  /// </remarks>
  [Test]
  [Category("Unit")]
  public void Signature_MatchesTheSequenceGenuineFilesCarry() {
    var bits = new byte[24];
    IffDctvCodec.FillSignature(bits);

    Assert.That(bits, Is.EqualTo(new byte[] {
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
    }));
  }

  [Test]
  [Category("Unit")]
  public void WrittenFile_IsAnIlbmWithTheExpectedChunks() {
    var bytes = IffDctvWriter.ToBytes(IffDctvFile.FromRawImage(_Blank(320, 8)));

    Assert.Multiple(() => {
      Assert.That(bytes.AsSpan(0, 4).SequenceEqual("FORM"u8), Is.True);
      Assert.That(bytes.AsSpan(8, 4).SequenceEqual("ILBM"u8), Is.True);
      Assert.That(_Contains(bytes, "BMHD"u8), Is.True);
      Assert.That(_Contains(bytes, "CMAP"u8), Is.True);
      Assert.That(_Contains(bytes, "CAMG"u8), Is.True);
      Assert.That(_Contains(bytes, "BODY"u8), Is.True);
    });
  }

  private static bool _Contains(byte[] haystack, ReadOnlySpan<byte> needle) {
    for (var i = 0; i + needle.Length <= haystack.Length; ++i)
      if (haystack.AsSpan(i, needle.Length).SequenceEqual(needle))
        return true;

    return false;
  }

  private static RawImage _Blank(int width, int height) => new() {
    Width = width,
    Height = height,
    Format = PixelFormat.Rgb24,
    PixelData = new byte[width * height * 3],
  };
}
